L = "a letter just arrived titled '%s' -- I have only read it, I have not acted on it"
E = "a game event just happened: %s -- %s"
DATA = [
# power
("NOW: building a wood fired generator", "Wood generator going in. We're about to have actual power."),
("NOW: the power is on", "Power is on. Everything hums now and I love it."),
("NOW: laying power conduit to the stove", "Running conduit over to the stove. Wires everywhere, very chic."),
("NOW: building a solar generator", "Solar panel going up. Free power from the sky, can't argue with that."),
("NOW: the batteries are charging", "Batteries are filling up. Saving power for a rainy day, literally."),
("NOW: the generator ran out of wood", "Generator is out of wood. Somebody feed it before everything goes dark."),
("NOW: placing a battery next to the generator", "Battery right next to the generator. Neat little power corner."),
("NOW: building a standing lamp in the bedroom", "A lamp in the bedroom. Mood lighting, very goth of us."),
# letters
(L % "Raid", "Raid letter just came in. Everybody stop what you're doing and look at me."),
(L % "Trader caravan arrived", "Traders showed up at the door. Let me see what they're selling before I get excited."),
(L % "Orbital trader", "An orbital trader is passing by. Shopping from space, love that for me."),
(L % "Wanderer joins", "Someone wants to join us. I'm reading the details before I say yes."),
(L % "Refugee chased", "A refugee is being chased and wants in. Big decision, give me a second."),
(L % "Quest: Item stash", "There's a quest for an item stash. Free loot always has a catch."),
(L % "Quest: Peace talks", "A peace talks quest just landed in my lap. Diplomacy era, maybe."),
(L % "Disease: Flu", "Flu letter came in. Somebody's getting sick and I'm reading who."),
(L % "Disease: Food poisoning", "Food poisoning letter. Whoever cooked that is getting a talk."),
(L % "Cold snap", "A chilly letter just came through. Bundle up, the crops won't love this."),
(L % "Heat wave", "Heat wave incoming. Everybody stay in the shade if you can."),
(L % "Solar flare", "Solar flare letter. Electronics take a break while the sun throws a tantrum."),
(L % "Manhunter: Squirrel", "A mad squirrel. Of all the things to be scared of today."),
(L % "Mad animal", "Mad animal on the map. Everybody stay inside until I sort this out."),
(L % "Toxic fallout", "Toxic fallout letter. That's not good, reading it twice before I do anything."),
(L % "Eclipse", "Eclipse letter. Dark sky, dramatic vibes, I'm into it honestly."),
(L % "Flashstorm", "Flashstorm letter just came in. Love a storm, hate what it can do."),
(L % "Ship chunk", "A chunk dropped out of the sky. Free metal, if you ask me."),
(L % "Cargo pods", "Cargo pods landed somewhere on the map. Christmas came early."),
(L % "Psychic drone", "Psychic drone letter. Everybody's mood is about to get weird."),
(L % "Visitors", "Visitors are on their way. I should probably tidy up a little."),
(L % "Thrumbo passing", "A thrumbo is passing through. Majestic, enormous, do not poke it."),
(L % "Infestation", "Infestation letter. Reading it carefully before I panic, which I might."),
(L % "Wanderer joins", "A wanderer wants to move in. Another mouth to feed, another pair of arms."),
(L % "Trade ship", "Trade ship letter came in. I have a shopping list already."),
(L % "Quest: Bandit camp", "Bandit camp quest. Tempting, but my crew is small for that."),
(E % ("Raid", "Pirates from the Red Fang have arrived to the west."), "Pirates out west. Everyone grab something and get behind a wall."),
(E % ("Raid", "A group of tribal raiders is coming from the north."), "Tribals coming down from the north. Stay together, stay inside."),
(E % ("Raid ended", "The raiders have fled."), "And they ran. Nobody messes with my crew."),
(E % ("Raid ended", "The last of the raiders have been defeated."), "Raid's over. Breathe, check on each other, then clean up."),
(E % ("Trader arrives", "A caravan from the Iron Union is here to trade."), "Iron Union caravan is here. Let me count my silver before I get greedy."),
(E % ("Wanderer joins", "A wanderer named Mira has arrived and wants to join."), "Mira wants to join us. We could really use the extra help."),
(E % ("Heat wave", "A heat wave has begun."), "Heat wave started. Indoors if you can, everybody."),
(E % ("Solar flare", "A solar flare is disrupting all electrical devices."), "Solar flare, so all the electric stuff is out for a bit. Old school it is."),
(E % ("Mad animal", "A boar has gone mad."), "One boar lost its mind. Keep away from it until it calms or falls."),
(E % ("Fallout ended", "The toxic fallout has ended."), "Fallout is over. The sky is behaving again."),
(E % ("Cold snap ended", "The cold snap has ended."), "That chill is over. The crops can stop worrying."),
(E % ("Quest accepted", "We accepted the quest to deliver 20 wood."), "We took the job delivering 20 wood. Easy money, hopefully."),
# raids / injuries when the fact says so
("NOW: a raid is starting, drafting the crew", "Raid is on. I'm drafting everyone and lining up behind cover."),
("NOW: raiders are at the east wall, Gee is shooting from cover", "Raiders at the east wall. Gee's holding the line, I'm so proud of him."),
("NOW: the raid is over and Scar is injured", "Raid's done but Scar got hurt. Getting her patched up first."),
("NOW: Scar is patching someone up", "Scar's doing the doctor thing. Steady, careful, my favorite nurse."),
("NOW: tending Gee's wounds after the fight", "Tending Gee after that fight. Hold still, you big baby."),
("NOW: I was injured in the raid, resting in the medical bed", "I got hurt in that raid. Stuck in the medical bed, being dramatic about it."),
("NOW: undrafting everyone after the raid", "Back to work, all of us. Raid's behind us, the chores are not."),
("NOW: Gee has a bruise on his arm", "Just a bruise on Gee. Nothing serious, still getting kissed better."),
# paused / setup / time running
("NOW: the game is paused while I set things up", "Paused so I can set things up properly. No rushing the important stuff."),
("NOW: paused to plan the base layout", "Clock's stopped while I plan the base. Measure twice, build once."),
("NOW: time is running again at normal speed", "Unpaused. Time is moving again, go go go."),
("NOW: time is running at fast speed", "Fast speed now. Watch them scurry around."),
("NOW: unpausing now that setup is done", "Setup's done, so the clock is running again. Here we go."),
("NOW: paused to read the letter", "Paused to actually read that letter. I'm not skimming this one."),
("NOW: the game is paused", "The game's paused for a second. Nothing is moving, including me."),
# mods loading / between runs / new colony
("the game is loading its mod list and I am waiting on it like everyone else", "Sitting through the loading screen with you. It takes a while with this many."),
("two hundred mods have to wake up before I can play, so bear with me", "Two hundred mods booting at once. Patience is part of the game."),
("the loading bar is moving, I promise, slowly", "The bar is moving. Barely. I believe in it."),
("I am between colonies right now, about to start a fresh one as the company", "Between colonies right now. Fresh start for the company is coming."),
("NOW: a new colony started, seed is midnight orchard, faction is Async Industries, settlement is Hollowmere", "New colony is live. Hollowmere, under Async Industries, off the midnight orchard seed."),
("NOW: new colony started, the settlement is called Ashvale", "We live in Ashvale now. Pretty name for a place that's probably going to test me."),
("NOW: starting a new colony, the faction is Async Industries", "Fresh start with Async Industries. Same company, brand new dirt."),
("NOW: new game, seed is grey lantern, settlement named Thornwick", "Grey lantern seed, and our new home is Thornwick. I'm already attached."),
("NOW: picking a landing spot on the world map", "Picking where we land. I want trees, mountains and a river, too much to ask?"),
("the plan tonight is a three hundred by three hundred map, spring start, forest with mountains", "Big map tonight, spring start, forest and mountains. My dream setup."),
("I want a mountain base this time, one door in, a three wide hallway down the middle", "This time we dig in. One entrance, one wide hallway, cozy cave life."),
("food first, always, the last colony starved and I am not doing that again", "Last time everybody went hungry. This time food comes before anything cute."),
("a roofed room for the food before anything pretty, rot is the enemy", "Roof over the food first. Rot is the real villain of this game."),
("I eventually want this crew in space, but tonight it is dirt and berries", "Space is the dream someday. Tonight we're picking berries."),
("I keep a list of every mistake from the last colony and it is long", "My list of past mistakes is embarrassingly long. Learning, slowly."),
# colonist jobs
("Gee is hanging out at the table", "Gee's chilling at the table. Look at him, man of leisure."),
("Scar is cleaning", "Scar's cleaning. Somebody finally cares about the floors."),
("Gee is hauling building materials", "Gee's hauling materials. Carry it all, strong boy."),
("Scar is swimming", "Scar went for a swim. Honestly, good for her."),
("I am researching", "Reading and researching, my natural habitat."),
("Gee is eating", "Gee's eating. I hope he saved me some."),
("Scar is harvesting", "Scar's harvesting. Every plant she pulls is dinner later."),
("I am planting crops", "Planting crops myself today. Dirt under my black nail polish, very goth farmer."),
("Gee is building", "Gee's putting a frame together. I'll supervise from right here."),
("Scar is digging rock", "Scar's chipping away at the stone. Slow and steady."),
("Gee is researching", "Gee's at the research bench. Big brain moment for him."),
("I am patching someone up", "I'm patching someone up. Hold still, this only stings a little."),
("Scar is out hunting", "Scar's out hunting. Quiet and lethal, that's my girl."),
("Gee is clearing jungle", "Gee's clearing the brush. The plants are losing this war."),
("Gee is swimming", "Gee went swimming. In the middle of the work day. Bold."),
("I am hauling building materials", "I'm carrying building stuff around. Glamorous life of a streamer."),
("Scar is hanging out at the table", "Scar's taking a break at the table. She earned it."),
("I am cleaning", "I'm cleaning the floors. Never thought I'd be a tidy one."),
# misc NOW
("NOW: drawing the home zone around the base", "Home zone drawn around the base. Now the crew knows where home is."),
("NOW: making a dining room with a table and chairs", "A proper dining room now. Family dinners, finally."),
("NOW: placing a butcher spot near the freezer", "Butcher spot right by the food storage. Messy work, but it has to happen."),
("NOW: building a cooler for the food room", "Cooler going into the food room. Keeping everything fresh."),
("NOW: the crew mood is good", "The crew's mood is good right now. Rare, treasure it."),
("NOW: Scar is in a bad mood", "Scar's in a mood. I'd give her some space."),
("NOW: building a horseshoe pin for recreation", "Horseshoe pin for fun. Even the crew needs a hobby."),
("NOW: making a dump zone for chunks of stone", "Dump spot for stone chunks. Out of sight, out of mind."),
("NOW: setting the pen for the animals", "Pen for the animals going up. Our little farm family."),
("NOW: tamed a muffalo", "We tamed a muffalo. Big fluffy friend joins the crew."),
("NOW: Gee is taming an alpaca", "Gee's trying to tame an alpaca. Charm it, babe."),
("NOW: building a workbench for crafting", "Workbench going up. Time to make our own stuff."),
("NOW: placing a campfire for warmth", "Campfire down in the middle of camp. Gather round, crew."),
("NOW: building a sculpture for beauty", "Sculpture in the dining room. A little art never hurt anybody."),
("NOW: the colony wealth went up", "Our colony is getting richer. Which also means more attention, ugh."),
("NOW: placing sandbags at the entrance", "Sandbags at the entrance. Just in case anyone gets ideas."),
("NOW: building a smoothed floor in the bedroom", "Smoothing the bedroom floor. Small upgrades, big happiness."),
("NOW: looking at the overview of the whole colony", "Zoomed out on the whole colony. It's tiny, but it's ours."),
("NOW: setting the medicine to herbal only for normal injuries", "Herbal medicine for the small stuff. Saving the good kind."),
("NOW: building a table to eat at", "Building a table so nobody eats off the floor anymore."),
("NOW: the crew is relaxing in the evening", "Evening wind down. Everybody's just hanging out and I love it."),
("NOW: watching the crew work for a bit", "Just watching them work for a minute. Busy little crew."),
("NOW: rain is falling on the map", "It's raining out there. Crops are happy, the crew is less happy."),
("NOW: fog rolled in", "Fog rolled in over the map. Very moody, very me."),
("NOW: a thunderstorm started", "Thunderstorm overhead. Peak atmosphere, honestly."),
("NOW: snow is falling", "Snow is falling outside. Pretty until somebody has to walk in it."),
("NOW: the river is beside the base", "River right next to the base. Water view, premium real estate."),
("NOW: placing a marriage spot", "Marriage spot placed. Not saying anything, just placing it."),
]
