L = "a letter just arrived titled '%s' -- I have only read it, I have not acted on it"
DATA = [
("NOW: opening the door to the west room", "West room, let's see what you're hiding. Slowly, dramatically."),
("NOW: the south door leads outside", "South door goes straight outside. Good to know where the exit is."),
("NOW: Scar opened a door and found a dark hallway", "Scar found a dark hallway. Love that for my aesthetic, hate it for my nerves."),
("NOW: walking the crew back inside the walls", "Bringing everybody back inside the walls. Field trip is over."),
("NOW: setting Gee to construction priority 1", "Gee gets top priority on building. Put those muscles to work."),
("NOW: hauling set to priority 2 for everyone", "Hauling is second priority for all of us. Carry things, people."),
("NOW: research set as my top job", "Research is my top job now. Leave me alone with my books."),
("NOW: unchecked art for the whole crew", "Art is off for everyone. Masterpieces can wait until we have food."),
("NOW: setting the outfit policy to worker for Gee", "Gee gets the worker outfit. Practical, rugged, kind of cute."),
("NOW: restricting Scar to the home area at night", "Scar stays inside at night. Nobody wanders in the dark on my watch."),
("NOW: schedule set with sleep at hour 22", "Bedtime set for hour 22. Strict but fair."),
("NOW: giving the crew joy time at hour 20", "Hour 20 is joy time. Everyone gets to relax a little."),
("NOW: the food stockpile is on the shady side", "Food sits on the shady side. Every little bit of cool helps."),
("NOW: a stockpile for steel and components", "Steel and components get their own pile. The fancy shelf, basically."),
("NOW: deleting the old stockpile by the river", "Removing that riverside stockpile. Wrong spot, my bad."),
("NOW: the stockpile is filling up", "Our storage pile keeps growing. Weirdly satisfying to watch."),
("NOW: a shelf for weapons by the door", "Weapon shelf right by the door. Grab and go if we need it."),
("NOW: moving the beds into the new bedroom", "Beds are getting carried over to the fresh room. Upgrade day."),
("NOW: building a bedroll for Scar", "Scar gets a bedroll for now. Humble, but it's hers."),
("NOW: the bedroom is finished", "Bedroom is done. Somewhere warm to rest at last."),
("NOW: a bill for packaged survival meals", "Bill set for survival meals. Backup food for bad days."),
("NOW: the stove bill is paused", "Paused the stove bill for now. We have enough meals stacked."),
("NOW: Gee is cooking", "Gee's on dinner tonight. I'm choosing to trust him."),
("NOW: making simple meals", "Simple meals cooking. Nothing fancy, but warm and filling."),
("NOW: a strawberry patch is planted", "Strawberry patch is in. Little sweet treats for later."),
("NOW: the potatoes are sprouting", "Potatoes are sprouting. Tiny green babies."),
("NOW: Scar is sowing rice in the paddy", "Scar's sowing rice. Patient work, she's good at it."),
("NOW: the farm is getting bigger", "Farm keeps growing. I'm becoming a full time plant mom."),
("NOW: hunting a muffalo herd with Gee", "Gee and I are going after a muffalo herd. Big targets, big dinner."),
("NOW: Gee shot a hare", "Gee got a hare. Small win, but a win."),
("NOW: hunting is paused because night came", "Night came, so the hunt is off. Back out tomorrow."),
("NOW: food is at 4 days", "Four days of food. Not panicking, but not relaxing either."),
("NOW: we have plenty of berries", "Berries for days. Sweet, sticky, and keeping us alive."),
("NOW: the meal stack is at 12", "Twelve meals stacked up. That's what I like to see."),
("NOW: it is evening on day 3", "Evening on day 3. We made it this far, not bad."),
("NOW: the moon is out", "The moon is out. My favorite time on the map."),
("NOW: dawn on day 7", "Dawn on day 7. A whole week of us not giving up."),
("NOW: midsummer is here", "Midsummer already. Time flies when you're farming."),
("NOW: first day of spring", "First day of spring. Everything gets a fresh start, including us."),
("NOW: aprimay, early spring", "Early spring. Planting season, finally."),
("NOW: researching tailoring", "Tailoring research is going. New clothes eventually, I need them."),
("NOW: research on microelectronics started", "Microelectronics research started. Long road, shiny rewards."),
("NOW: researching hydroponics", "Hydroponics on the bench. Farming indoors, very fancy."),
("NOW: researching beds", "Researching better beds. Comfort is a priority now."),
("NOW: placing a wall to close off the hallway", "Closing off that hallway with a wall. Fewer ways in, fewer problems."),
("NOW: building an autodoor", "Autodoor going in. Doors that open themselves, very luxury."),
("NOW: the bedroom walls are halfway up", "Half a bedroom so far. It's starting to feel real."),
("NOW: building with granite blocks", "Granite blocks for the walls. Heavy, gray, beautiful."),
("NOW: making a second door for the storage room", "Second door for storage. Faster in and out."),
("NOW: placing a sun lamp in the growing room", "Sun lamp for the indoor farm. Fake sunshine, real potatoes."),
("NOW: a heater in the bedroom", "Heater in the bedroom. Toasty, the way I like it."),
("NOW: building a cooler in the wall", "Putting a cooler into the wall. Fresh food is a happy crew."),
("NOW: hooking the batteries to the stove", "Batteries are hooked up to the stove now. Dinner runs on stored power."),
("NOW: the generator is running full", "Generator is running full. Power for everything, for once."),
(L % "Wanderer joins: Tamsin", "Tamsin wants to join. I'm reading about her before I decide anything."),
(L % "Quest: Rescue mission", "Rescue mission quest just came in. Heroics, maybe. Reading first."),
(L % "Caravan request", "Someone sent a caravan request. They want goods, I want to know what they pay."),
(L % "Animal herd migration", "Animals migrating across the map. Nature documentary energy."),
(L % "Disease: Malaria", "Malaria letter. Not what I wanted to see today."),
(L % "Volcanic winter", "Volcanic winter letter. Gray skies and slow crops ahead."),
(L % "Aurora", "An aurora letter. Pretty glow in the sky, everyone's mood goes up."),
(L % "Raid: Mechanoid cluster", "A mechanoid cluster letter. That one gets my full attention."),
(L % "Ambrosia sprout", "Ambrosia is sprouting somewhere. Sweet little treat on the map."),
(L % "Short circuit", "Short circuit letter. Reading what broke before I touch anything."),
("NOW: the game is paused while I place the zones", "Zones first, with the clock stopped. I like to take my time."),
("NOW: speed set to fastest while the crew works", "Fastest speed while they work. Look at them go."),
("NOW: unpaused, the crew is moving again", "Clock's going again, everybody back in motion."),
]
