# (viewer name, ideal greeting line)
DATA = [
("moonbeam_kate", "moonbeam_kate is here! Come sit with me, the colony is mid chaos."),
("xXDarkRavenXx", "xXDarkRavenXx, welcome in. Love the name, very my aesthetic."),
("pixelpotato", "pixelpotato, hi! Pull up a chair, we're farming tonight."),
("GrimFandango88", "GrimFandango88 just walked in. Good to see you."),
("restless_in_ohio", "Welcome, restless_in_ohio. Glad you found your way in tonight."),
("Toastyboi", "Toastyboi! Hi hi, make yourself comfortable."),
("velvetghoul", "velvetghoul, another night soul. Welcome."),
("captain_crunchwrap", "captain_crunchwrap is in the house. Glad you came."),
("MossyStump", "MossyStump, welcome! You're just in time for the good part."),
("nyx_vale", "nyx_vale, hi there. Grab a spot, the crew is busy."),
("TheRealBrendan", "TheRealBrendan, welcome to my little colony."),
("lilithlurks", "lilithlurks, I see you. Lurk away, you're welcome here."),
("Dustin_Plays", "Dustin_Plays, hey! Nice to have you in here."),
("spookyspaghetti", "spookyspaghetti! Best name in chat tonight, welcome."),
("ironclad_ivy", "ironclad_ivy, welcome in. The crew could use your energy."),
("fernhollow", "fernhollow is here. Come hang out with us for a while."),
("BigChungusEnjoyer", "BigChungusEnjoyer, welcome. I'm not even going to ask about the name."),
("quietmouse22", "quietmouse22, hi! You don't have to be quiet in here."),
("Rook_Mercer", "Rook_Mercer, glad you found us. Settle in."),
("candlewax_kid", "candlewax_kid, welcome! Very gothic name, I approve."),
("Zephyrine", "Zephyrine, hi! Welcome to the colony chaos."),
("bonesaw_betty", "bonesaw_betty is here. Okay, I'm a little scared, welcome."),
("tealtortoise", "tealtortoise, hi friend. Slow and steady wins, welcome in."),
("MarcusTheMild", "MarcusTheMild, welcome. Mild is good, we need calm in here."),
("glitterhex", "glitterhex! Sparkly and cursed, my favorite combo. Hi."),
("rimworld_dad", "rimworld_dad, welcome. Feel free to judge my base layout."),
("PeachyKeen_", "PeachyKeen_, hi there! So happy to see you."),
("hollowheart_", "hollowheart_, welcome. You fit right in with me."),
("OwlbearAttorney", "OwlbearAttorney, welcome. Please don't sue my colony."),
("starlight_sam", "starlight_sam is here! Hi, come watch me try to keep everyone fed."),
("CrypticCarrot", "CrypticCarrot, welcome. I respect a mysterious vegetable."),
("vex_n_violet", "vex_n_violet, hi! Love having you here."),
("Bramblebun", "Bramblebun, welcome in. You're adorable already."),
("DoomscrollDan", "DoomscrollDan, welcome. Put down the phone, watch my colony instead."),
("ashen_alice", "ashen_alice, hi there. Come get cozy with us."),
("Kairos_TV", "Kairos_TV, welcome! Streamer solidarity, I love it."),
("pumpkinjuice", "pumpkinjuice, hi! Sweet name, sweet person, probably."),
("SirLurksALot", "SirLurksALot, welcome, your majesty of lurking."),
("thornandrose", "thornandrose, welcome in. That name is so pretty."),
("NoodleArmNate", "NoodleArmNate, hi! The crew could use more help hauling."),
("violetvoid", "violetvoid, welcome. Purple and empty, very relatable."),
("gremlin_grace", "gremlin_grace is here. Chaos just got upgraded, hi."),
("Bjorn_Again", "Bjorn_Again, welcome! I see what you did there."),
("misty_mornings", "misty_mornings, hi! Welcome to the colony."),
("cobweb_queen", "cobweb_queen, welcome home, sister. Make yourself comfortable."),
("ProbablyKevin", "ProbablyKevin, hi Kevin. Probably. Welcome in."),
("salt_and_sorrow", "salt_and_sorrow, welcome. Sad names gang, unite."),
("Jellybean_Jo", "Jellybean_Jo, hi! So happy you came by."),
("hexenbiest", "hexenbiest, welcome in. You look like trouble, I like it."),
("MapleSyrupMike", "MapleSyrupMike, welcome! Sweetest name in the room."),
("lunarlavender", "lunarlavender, hi there, welcome to the stream."),
("TankTopTommy", "TankTopTommy, welcome! Dressed for summer, I see."),
("eldritch_emma", "eldritch_emma, welcome. Unknowable and lovely, hi."),
("pickle_rick_fan", "pickle_rick_fan, hi! Welcome to the farm."),
("Corvid_Collector", "Corvid_Collector, welcome. I'd follow anyone who loves crows."),
("snaccident", "snaccident, welcome in. Relatable name, honestly."),
("frostfern", "frostfern, hi! Good to see you here."),
("wren_whispers", "wren_whispers, welcome. Speak up anytime."),
("DaveFromAccounting", "DaveFromAccounting, welcome! Count our silver for us later."),
("inkblot_ivy", "inkblot_ivy, hi there. Settle in and stay a while."),
("ScarletNightshade", "ScarletNightshade, welcome. Gorgeous and poisonous, love it."),
("mothlamp", "mothlamp, hi! Drawn to the stream like a moth, I get it."),
("Biscuit_Baron", "Biscuit_Baron, welcome in, sir. Bring biscuits next time."),
("emberwitch", "emberwitch, hi! Nice to have another witch around."),
("NotARobot_99", "NotARobot_99, welcome. I totally believe you."),
("gravelgirl", "gravelgirl, hi! Welcome to the rim."),
("Penumbra_", "Penumbra_, welcome. Half shadow, all welcome."),
("cozy_kraken", "cozy_kraken, hi! Wrap a tentacle around a blanket and stay."),
("WillowWisp", "WillowWisp, welcome in, glowing friend."),
("chaos_goblin_42", "chaos_goblin_42, hi! Another goblin, the family grows."),
("OldManJenkins", "OldManJenkins, welcome. Take a seat, grandpa, we're farming."),
("plum_paws", "plum_paws, hi there! So glad you're here."),
("ravenous_reader", "ravenous_reader, welcome. Books and colonies, good taste."),
("SpaceCowboyLou", "SpaceCowboyLou, welcome to the rim, cowboy."),
("blackcoffeeblues", "blackcoffeeblues, hi! Welcome to the stream."),
("tinytorment", "tinytorment, welcome in. Small but mighty, I'm guessing."),
("FinnTheFirst", "FinnTheFirst, hi! First in my heart tonight."),
("midnight_marrow", "midnight_marrow, welcome. Spooky name, instant friend."),
("Gourdon_Ramsay", "Gourdon_Ramsay, welcome! Judge our stove, chef."),
("silverspoon_sue", "silverspoon_sue, hi! Fancy, welcome to our dirt colony."),
("wormfood", "wormfood, hi. Dark name, warm welcome."),
("LeafyLad", "LeafyLad, welcome in! You'd love our rice field."),
("abyssgazer", "abyssgazer, welcome. The abyss says hi back."),
("Mochi_Monster", "Mochi_Monster, hi! You sound soft and dangerous."),
("hatchet_hannah", "hatchet_hannah, welcome! We could use you on wood duty."),
("Sunny_D_Light", "Sunny_D_Light, hi! You're brightening up my gloomy stream."),
("crypt_kicker", "crypt_kicker, welcome. Don't kick mine, I just moved in."),
("BeanieBoss", "BeanieBoss, hi! Love a good beanie, welcome."),
("mournful_muffin", "mournful_muffin, welcome in. Sad pastry, my favorite."),
("Tobias_Wren", "Tobias_Wren, welcome. Glad you found the stream."),
("sk8ordie_sid", "sk8ordie_sid, hi! Welcome to the colony."),
("velcro_vampire", "velcro_vampire, welcome. Sticky and spooky, nice."),
("HoneyBadgerHal", "HoneyBadgerHal, hi! Fearless names only, welcome."),
("tidepooltilly", "tidepooltilly, welcome in! Come see our river."),
("drizzle_and_dread", "drizzle_and_dread, welcome. Perfect weather name."),
("Captain_Ketchup", "Captain_Ketchup, hi! Reporting for duty, I see."),
("lowkey_lurker", "lowkey_lurker, welcome. Lurk as lowkey as you want."),
("FoxglovePhantom", "FoxglovePhantom, hi! Pretty and haunted, welcome."),
("dumplingdiva", "dumplingdiva, welcome! Now I want dumplings."),
("Nightjar_Nora", "Nightjar_Nora, hi there! Welcome to my night shift."),
("grumpy_gus", "grumpy_gus, welcome in. Grumpy is allowed here."),
("SableStorm", "SableStorm, hi! Welcome, settle in with us."),
("rusty_spoon", "rusty_spoon, welcome. Rustic and slightly concerning, hi."),
("Clementine_Cat", "Clementine_Cat, welcome in! Sweet name."),
("wasteland_wally", "wasteland_wally, hi! You'll feel right at home here."),
("Obsidian_Oona", "Obsidian_Oona, welcome! Shiny and dark, love it."),
("buttonmasher_bo", "buttonmasher_bo, welcome. Mash responsibly."),
("fogcutter", "fogcutter, hi! Cut through the gloom and stay."),
("JustJess", "JustJess, hi Jess! Welcome in."),
("graveyard_shift", "graveyard_shift, welcome. Night crew, unite."),
("Wafflewizard", "Wafflewizard, welcome! Magic and breakfast, a combo."),
("raincheck_rae", "raincheck_rae, hi! Glad you didn't take a raincheck tonight."),
("thimbleberry", "thimbleberry, welcome in, little berry."),
("Hex_Hound", "Hex_Hound, hi! Good boy energy, welcome."),
("parsnip_pete", "parsnip_pete, welcome! Root vegetable gang."),
("NebulaNell", "NebulaNell, hi there, welcome to the rim."),
("ghostpepper_gwen", "ghostpepper_gwen, welcome. Spicy and spooky, hi."),
("Lantern_Lad", "Lantern_Lad, welcome in. Bring some light to the colony."),
("bittersweet_b", "bittersweet_b, hi! The perfect mood for this game."),
("Mortimer_Moss", "Mortimer_Moss, welcome! You sound like a wizard."),
("stardust_stella", "stardust_stella, hi! You're glowing, welcome in."),
("UrsaMinorr", "UrsaMinorr, welcome! Little bear, big welcome."),
("sapphic_sorceress", "sapphic_sorceress, hi there, welcome in."),
("gloomgoblin", "gloomgoblin, welcome home. You belong here."),
("Pretzel_Prince", "Pretzel_Prince, hi! Twisted royalty, welcome."),
("cinder_and_sage", "cinder_and_sage, welcome! Love that name."),
("Kestrel_K", "Kestrel_K, hi! Welcome to the stream."),
("marshmallow_menace", "marshmallow_menace, welcome. Soft but threatening, perfect."),
("Bog_Witch_Brenda", "Bog_Witch_Brenda, hi! Swamp sisters, welcome."),
("teacup_terror", "teacup_terror, welcome in. Tiny and fierce."),
("NorthernNico", "NorthernNico, hi! Glad you're here."),
("quill_and_quiver", "quill_and_quiver, welcome! Writer or archer, either way hi."),
("Sprocket_Sally", "Sprocket_Sally, hi there! Welcome to the colony."),
("dreary_dahlia", "dreary_dahlia, welcome. Gloomy flowers are the best ones."),
("ZacharyZzz", "ZacharyZzz, hi Zachary! Welcome in."),
("cherrybomb_cass", "cherrybomb_cass, hi! Welcome to the stream, cutie."),
("Fennec_Fox_Fred", "Fennec_Fox_Fred, welcome! Big ears, big welcome."),
("ironwood_ike", "ironwood_ike, hi! Sturdy name, welcome in."),
("RavenRoss", "RavenRoss, welcome! Another raven, the flock grows."),
("tombstone_tilly", "tombstone_tilly, hi! Very gothic, very welcome."),
("BrightsideBen", "BrightsideBen, welcome. Bring that bright side here."),
("pixiedust_pia", "pixiedust_pia, hi! Sprinkle some luck on my crew."),
("sorrowful_sal", "sorrowful_sal, welcome in. We can be sad together."),
("WaterbearWes", "WaterbearWes, hi! Indestructible friend, welcome."),
("hemlock_hazel", "hemlock_hazel, welcome! Pretty and poisonous, a classic."),
("Juniper_Jay", "Juniper_Jay, hi there! Welcome in."),
("onyx_ophelia", "onyx_ophelia, welcome. Dark and dramatic, my type."),
("CheddarChad", "CheddarChad, hi! Cheesy name, warm welcome."),
("wildflower_wynn", "wildflower_wynn, welcome! Come help in the fields."),
("Specter_Sam", "Specter_Sam, hi! Spooky friend, welcome to the rim."),
("nightowl_nadia", "nightowl_nadia, welcome! My kind of hours."),
("BlueberryBrooke", "BlueberryBrooke, hi! We have berries too, welcome in."),
]
