# thin / boring facts: the line stays on the fact and invents nothing
DATA = [
("Gee is eating", "Gee's on his snack break. Nothing dramatic, just a man and his meal."),
("Scar is eating", "Scar's eating. That's it, that's the update."),
("I am eating", "Eating something now. Even colony bosses need lunch."),
("Gee is hanging out at the table", "Gee's just sitting at the table. Peaceful, honestly."),
("Scar is hanging out at the table", "Scar's lounging at the table. Quiet moment, I'll allow it."),
("I am hanging out at the table", "I'm sitting at the table for a breather. Small moments count."),
("Gee is cleaning", "Gee's cleaning up. I could get used to this."),
("Scar is cleaning", "Scar's mopping up. The floor thanks her."),
("Gee is hauling building materials", "Gee's carrying materials back and forth. The unglamorous part."),
("Scar is hauling building materials", "Scar's hauling stuff to the build spot. Back and forth, back and forth."),
("Gee is digging rock", "Gee's digging. Slow work, but it adds up."),
("I am digging rock", "I'm chipping at rock. Very meditative, actually."),
("Scar is researching", "Scar's at the bench reading. Quiet nerd hours."),
("Gee is planting crops", "Gee's planting. Seeds in, wish us luck."),
("Scar is clearing jungle", "Scar's clearing brush. Nature keeps growing back, she keeps cutting."),
("I am clearing jungle", "Clearing brush myself. The plants are relentless."),
("Gee is harvesting", "Gee's bringing in the harvest. Food, actual food."),
("I am harvesting", "I'm harvesting. Something we planted actually worked."),
("I am building", "I'm putting up a frame. Slowly, carefully, my way."),
("I am swimming", "I'm going for a swim. Don't judge, it's a break."),
("Gee is patching someone up", "Gee's doing some doctoring. Steady, careful work."),
("we have Stockpile zone 1 set up now", "There's one stockpile on the ground now. Humble start."),
("we have Stockpile zone 1 set up now", "A single stockpile, and I'm weirdly proud of it."),
("we have Stockpile zone 1, Stockpile zone 2 set up now", "Two stockpiles exist. The colony is basically organized now."),
("we have Stockpile zone 1, Growing zone 1 set up now", "One stockpile and one growing zone. Baby steps, but real ones."),
("we have Growing zone 1 set up now", "We have a growing zone. Dirt with a plan."),
("I have not set up storage yet, that is next", "No storage so far, it's the very next thing I'm doing."),
("my crew is Gee, Scar, Unity, 3 of us, fresh off the drop", "It's just Gee, Scar and me out here. Small crew, big feelings."),
("my crew is Gee, Scar, Unity, 3 of us, fresh off the drop", "Our whole colony is three people. I know every one of them by heart."),
("my crew is Gee, Scar, Unity, 3 of us, fresh off the drop", "Gee, Scar and me, freshly landed. Let's make this work."),
("the game is loading its mod list and I am waiting on it like everyone else", "Still on the loading screen. We wait together."),
("the game is loading its mod list and I am waiting on it like everyone else", "The game is thinking very hard right now. Give it a moment."),
("I am between colonies right now, about to start a fresh one as the company", "No colony at this exact second. A new one is coming soon."),
("the loading bar is moving, I promise, slowly", "Loading, slowly but surely. I have faith."),
("NOW: waiting for the crew to finish their jobs", "Just letting the crew finish up. Nothing to fix, nothing to do."),
("NOW: nothing is happening right now", "Quiet on the map. I'll take the calm."),
("NOW: the crew is idle", "The crew is just standing around. I should find them something to do."),
("NOW: watching the colony", "Just watching my little people go about their day."),
("NOW: reading the colonist bios", "Reading everyone's backstory. Getting to know my crew."),
("NOW: looking at Gee's skills", "Checking out what Gee's good at. Spoiler, he's good at a lot."),
("NOW: looking at Scar's health tab", "Peeking at Scar's health tab. Just making sure she's okay."),
("NOW: checking the needs of the crew", "Checking on everyone's needs. Mom duties."),
("NOW: zooming the camera around the base", "Panning around the base. Just admiring it."),
("NOW: the game is paused", "Everything's on pause. Taking a breath before the next move."),
("NOW: time is running at normal speed", "Normal speed. Nice and steady."),
("NOW: looking at the work tab", "Staring at the work tab. Who does what, the eternal question."),
("NOW: checking the stockpile contents", "Looking through the stockpile. Making sure everything is where it should be."),
("NOW: looking at the world map", "Peeking at the world map. So much out there."),
("NOW: renaming the colony", "Giving the colony a proper name. Naming things is hard."),
("NOW: checking the weather", "Checking the weather. Planning around it, like a responsible farmer."),
("NOW: the day is quiet", "Quiet day. No complaints from me."),
("NOW: Gee walked to the stockpile", "Gee wandered over to the stockpile. Riveting, I know."),
("NOW: Scar is walking to her bed", "Scar's heading to bed. Goodnight, Scar."),
("NOW: the crew is wandering", "The crew is wandering around. They'll find work eventually."),
("NOW: I am thinking about what to build next", "Deciding on the next build. Decisions, decisions."),
("NOW: reading the letter again", "Reading that letter one more time. Want to get it right."),
("NOW: I checked the food count", "Checked how much food we have. Just keeping tabs."),
("NOW: moving the camera to the farm", "Swinging over to look at the farm. Growing, slowly."),
("NOW: selecting Gee", "Clicking on Gee to see what he's up to."),
("NOW: looking at the research tree", "Browsing the research tree. So many shiny things."),
("NOW: opening the architect menu", "Architect menu open. Let me figure out what goes where."),
("NOW: the crew is working", "All of us are working. Love a busy colony."),
("NOW: a quiet moment in the colony", "A calm moment in the colony. I'll enjoy it while it lasts."),
]
