# -*- coding: utf-8 -*-
"""The solo/group start: def field, start def, scenario def, generator def, manifest."""
import io
import json
import os
import xml.etree.ElementTree as ET

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MOD = os.path.join(REPO, 'Mod', 'Rimrooms - Async Industries', '1.6')


def sub(path, old, new, enc='utf-8-sig'):
    s = io.open(path, encoding=enc).read()
    assert old in s, '%s: anchor missing %r' % (os.path.basename(path), old[:70])
    assert s.count(old) == 1, '%s: anchor not unique' % os.path.basename(path)
    io.open(path, 'w', encoding=enc, newline='').write(s.replace(old, new, 1))


# ------------------------------------------------------------------ the def field
p = os.path.join(REPO, 'src', 'RimroomsAsyncIndustries', 'Scenario', 'RimroomsStartDef.cs')
sub(p, u'        public long initialFundingUsd = 50000000L;',
u"""        /// <summary>
        /// This start opens INSIDE a Backrooms coordinate rather than on a surface tile.
        ///
        /// It changes what a layout means. A surface start declares rooms, doors, buildings and
        /// conduits and `GenStep_Headquarters` builds them. An inside start declares none of
        /// those: the map IS the coordinate, generated by `GenStep_InsideStart` from a room
        /// graph, and there is no facility to place because nobody built one.
        /// </summary>
        public bool insideStart;

        /// <summary>How deep the coordinate is. Higher is deeper; depth 1 is the yellow rooms.</summary>
        public int insideStartDepth = 1;

        public long initialFundingUsd = 50000000L;""", 'utf-8-sig')

sub(p, u"""            if (rooms == null || buildings == null || stock == null || doors == null || conduits == null)
            { yield return "Missing headquarters layout/stock list."; }""",
u"""            if (rooms == null || buildings == null || stock == null || doors == null || conduits == null)
            { yield return "Missing headquarters layout/stock list."; }
            // An inside start has no facility to declare, and declaring one would be built on
            // top of a coordinate that is already wall to wall.
            if (insideStart && (rooms.Count > 0 || doors.Count > 0 || buildings.Count > 0 || conduits.Count > 0))
            { yield return "An inside start declares no rooms, doors, buildings or conduits; the map is the coordinate."; }
            if (insideStart && (insideStartDepth < 1 || insideStartDepth > 9))
            { yield return "Inside start depth must be between 1 and 9."; }
            if (!insideStart && rooms != null && rooms.Count < 1)
            { yield return "A surface start needs at least one room."; }""", 'utf-8-sig')

# ------------------------------------------------------------------ the generator
p = os.path.join(MOD, 'Defs', 'MapGeneratorDefs', 'RR_BackroomsGeneration.xml')
sub(p, u'\n</Defs>', u"""
  <!-- The solo/group start's map. Core picks the starting map's generator as
       initData.mapGeneratorDef ?? settlement.MapGeneratorDef, and ScenPart_RimroomsStart has
       always assigned that field from the start def, so naming this here is the whole trick.
       No Harmony and no patching of anybody's defs.

       ScenParts runs after the layout so the native starting things land in carved rooms
       rather than in solid rock. -->
  <MapGeneratorDef>
    <defName>RR_InsideStart</defName>
    <genSteps>
      <li>RR_InsideStartLayout</li>
      <li>ScenParts</li>
      <li>Fog</li>
    </genSteps>
  </MapGeneratorDef>

  <GenStepDef>
    <defName>RR_InsideStartLayout</defName>
    <order>800</order>
    <genStep Class="RimroomsAsyncIndustries.Scenario.GenStep_InsideStart" />
  </GenStepDef>

</Defs>""")
ET.parse(p)
print('inside-start generator def written')

# ------------------------------------------------------------------ the start def
p = os.path.join(MOD, 'Defs', 'RimroomsStartDefs', 'RR_Starts.xml')
sub(p, u'\n</Defs>\n', u"""
  <!-- ==================================================================================== -->
  <!-- SOLO / GROUP - THE INSIDE START                                                      -->
  <!--                                                                                      -->
  <!-- Contract: docs/SCENARIOS.md, the lone_survivor card. The stable scenario ID is kept   -->
  <!-- because saves depend on it; the NAME is solo/group, on owner direction: "remember     -->
  <!-- the other one is solo/group start.. group have been known to end up together inside". -->
  <!--                                                                                      -->
  <!-- The map IS a Backrooms coordinate, wall to wall, so there is no layout to declare.    -->
  <!-- No corporation, no research, no facility, no gate and no way home. 1 to 5 people,     -->
  <!-- the player's choice, through the native config page.                                  -->
  <!--                                                                                      -->
  <!-- Funding is zero and overhead is zero, and both are deliberate: there is no company     -->
  <!-- here to run an account or bill a wage. Nobody is being paid and nobody is billing.     -->
  <!-- ==================================================================================== -->
  <RimroomsAsyncIndustries.Scenario.RimroomsStartDef>
    <defName>RR_SoloGroupStart</defName>
    <label>Solo or group, inside</label>
    <scenarioId>lone_survivor</scenarioId>
    <beginsInCorporationContact>false</beginsInCorporationContact>
    <defaultCompanyName>The ones who got in</defaultCompanyName>
    <scenarioVersion>1</scenarioVersion>
    <completedProjects />
    <insideStart>true</insideStart>
    <insideStartDepth>1</insideStartDepth>
    <mapSize>60</mapSize>
    <mapGenerator>RR_InsideStart</mapGenerator>
    <outdoorTerrain>Concrete</outdoorTerrain>
    <floorTerrain>Concrete</floorTerrain>
    <wallStuff>BlocksGranite</wallStuff>
    <!-- The generator decides where anybody can stand, because the rooms are generated. These
         two are required by the shared contract and are never read on an inside start. -->
    <arrivalCell>(30, 0, 30)</arrivalCell>
    <stockCell>(30, 0, 30)</stockCell>
    <rooms />
    <doors />
    <buildings />
    <conduits />
    <roles>
      <li>
        <id>operations</id><mustFight>false</mustFight>
        <skills><Social>3</Social><Intellectual>3</Intellectual></skills>
        <workTypes><li>Hauling</li></workTypes>
      </li>
    </roles>
    <initialFundingUsd>0</initialFundingUsd>
    <dailyWageUsd>0</dailyWageUsd>
    <dailyOverheadUsd>0</dailyOverheadUsd>
    <surveyRewardUsd>500000</surveyRewardUsd>
    <surveyBonusUsd>100000</surveyBonusUsd>
  </RimroomsAsyncIndustries.Scenario.RimroomsStartDef>

</Defs>
""")
ET.parse(p)
print('solo/group start def written')

# ------------------------------------------------------------------ the scenario
p = os.path.join(MOD, 'Defs', 'ScenarioDefs', 'RR_Scenarios.xml')
sub(p, u'\n  <MapGeneratorDef>', u"""
  <ScenarioDef ParentName="ScenarioBase">
    <defName>RR_SoloGroup</defName>
    <label>Solo or group, inside</label>
    <description>You are already in. There was no gate and there is no way back that anybody knows about.

The rooms go on further than you have walked. The roof does not come off. Nothing here was built for you and nothing here is coming for you, because no company knows this place exists and neither did you until today.

One to five people, your choice. Groups have been known to end up in together.

Stay alive, learn one rule this place obeys, mark the way you came, and decide whether you are looking for a way out, a way to call somebody, or somewhere to put a bed.</description>
    <scenario>
      <summary>You start inside the Backrooms with what you were carrying. No company, no gate, no research and nobody looking for you. One to five people.</summary>
      <parts>
        <li Class="ScenPart_ConfigPage_ConfigureStartingPawns">
          <def>ConfigPage_ConfigureStartingPawns</def>
          <pawnCount>1</pawnCount>
          <pawnChoiceCount>5</pawnChoiceCount>
          <allowedDevelopmentalStages>Adult</allowedDevelopmentalStages>
        </li>
        <li Class="RimroomsAsyncIndustries.Scenario.ScenPart_RimroomsStart">
          <def>RR_CompanyStart</def>
          <startDef>RR_SoloGroupStart</startDef>
          <visible>false</visible>
        </li>
        <li Class="RimroomsAsyncIndustries.Scenario.ScenPart_RimroomsArrival">
          <def>RR_CompanyArrival</def>
          <method>Standing</method>
          <visible>false</visible>
        </li>
        <!-- What you had on you. A light source matters more than anything else here, and
             the place has no power: nobody wired it and nobody is going to. -->
        <li Class="ScenPart_StartingThing_Defined"><def>StartingThing_Defined</def><thingDef>MealSurvivalPack</thingDef><count>5</count></li>
        <li Class="ScenPart_StartingThing_Defined"><def>StartingThing_Defined</def><thingDef>MedicineHerbal</thingDef><count>2</count></li>
        <li Class="ScenPart_StartingThing_Defined"><def>StartingThing_Defined</def><thingDef>RR_FieldRecorder</thingDef><count>1</count></li>
        <li Class="ScenPart_StartingThing_Defined"><def>StartingThing_Defined</def><thingDef>GlowPod</thingDef><count>3</count></li>
        <li Class="ScenPart_StartingThing_Defined"><def>StartingThing_Defined</def><thingDef>Steel</thingDef><count>40</count></li>
        <li Class="ScenPart_StartingThing_Defined"><def>StartingThing_Defined</def><thingDef>ComponentIndustrial</thingDef><count>2</count></li>
      </parts>
    </scenario>
  </ScenarioDef>

  <MapGeneratorDef>""")
ET.parse(p)
print('solo/group scenario written')
