# -*- coding: utf-8 -*-
"""What chases a crew is an ordinary pawn, hunting by Core's rules.

## Owner direction, 2026-10-04, verbatim

*"yeah things that chase you are just npc pawns and wild animals and shit of the
gasme spawned in procedurally and dynamically for randomness encounters, not
somew new type of np0c in the backrooms, they should be nutral, allies, and enemy
in all differnt kinds and relations and scenrios. not some blob figure, just
normal core mechanics"*

## THIS SUBSYSTEM HAD NO COVERAGE AT ALL, AND THAT IS WHY IT COULD BE A BLOB

Before this file there was **no proof and no plant anywhere** that mentioned the
pursuer. Twenty-three plant suites, forty-nine proofs, and a 224-line bespoke
threat that teleported between rooms, never pathfound, never opened a door and
landed one scripted two-point blow passed every gate this project has, for
twenty-seven versions. The instruments measured what they were pointed at.

So the claims below are written against the **properties the owner's direction
names**, not against the shape of the replacement:

  * the chaser is a `Pawn`, generated by Core's own `PawnGenerator`;
  * the roster is Core pawn kinds **and** the map biome's wild animals;
  * nothing teleports -- no assignment to a position anywhere in the file;
  * no scripted damage -- Core's combat does the hurting;
  * the bespoke thing and its def are **gone**, not merely unused;
  * the draw is derived from the branch seed, never `Rand`.

Run from the repository root. Exit status is the result.
"""
import io
import os
import re
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# `.local/register/<this>` -- THREE levels up. The first draft went two and resolved to
# `.local`, so every `read()` returned "" and **eight absence claims passed against empty
# strings**: *nothing teleports*, *nothing scripts damage*, *the counters are gone* and
# *nothing reaches for the retired def* are all trivially true of a file that was never read.
# An absence claim is worth only as much as the proof that its haystack exists, which is why
# `read()` below refuses an empty one.
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(REPO, "src", "RimroomsAsyncIndustries")
MOD = os.path.join(REPO, "Mod", "Rimrooms - Async Industries", "1.6")

failures = []


def check(claim, held, because=""):
    print("  %-4s %s %s" % ("OK" if held else "FAIL", claim, because if not held else ""))
    if not held:
        failures.append(claim)


def read(*parts):
    """Read a file that must exist and must have content.

    **A proof whose haystack is empty reports every absence claim as held.** The first run
    of this file did exactly that against a wrong repository root: eight claims green, all
    of them meaningless. Nothing here may degrade to "".
    """
    path = os.path.join(*parts)
    if not os.path.isfile(path):
        raise SystemExit("ABORT: %s does not exist, so no claim about it means anything"
                         % path)
    text = io.open(path, encoding="utf-8-sig").read()
    if not text.strip():
        raise SystemExit("ABORT: %s is empty, so no claim about it means anything" % path)
    return text


def strip_comments(text):
    """Code only. A claim that matches a doc comment describing the old behaviour is a lie."""
    out = []
    index = 0
    while index < len(text):
        if text[index] == '"':
            out.append(text[index])
            index += 1
            while index < len(text):
                if text[index] == "\\":
                    out.append(text[index:index + 2])
                    index += 2
                    continue
                out.append(text[index])
                if text[index] == '"':
                    index += 1
                    break
                index += 1
            continue
        if text.startswith("//", index):
            while index < len(text) and text[index] != "\n":
                index += 1
            continue
        if text.startswith("/*", index):
            end = text.find("*/", index + 2)
            index = len(text) if end == -1 else end + 2
            continue
        out.append(text[index])
        index += 1
    return "".join(out)


print("proof-chaser")
print("-" * 78)

chaser_raw = read(SRC, "Threats", "FirstSlicePursuer.cs")
chaser = strip_comments(chaser_raw)
site = strip_comments(read(SRC, "Threats", "FirstSliceSiteComponent.cs"))
observations = strip_comments(read(SRC, "Company", "EvidenceObservations.cs"))
site_objects = read(MOD, "Defs", "ThingDefs_Misc", "RR_SiteObjects.xml")

check("THE CHASER IS A POINTER TO A PAWN, not a bespoke thing",
      "private Pawn pursuer;" in site
      and "Thing_QuietPursuer" not in site,
      "-- it was `private Thing_QuietPursuer pursuer;`, and the owner's word for what that drew "
      "was *blob*")

check("and it is generated by Core's own generator",
      "PawnGenerator.GeneratePawn(new PawnGenerationRequest(" in chaser,
      "-- a chaser has a body, a backstory, gear, health and skills because it is a person or an "
      "animal, not a manifestation")

check("THE ROSTER IS CORE PAWN KINDS AND THE BIOME'S OWN WILD ANIMALS",
      'HostileHumanlikeKinds = { "Pirate", "Drifter", "Villager" }' in chaser
      and "map.Biome.AllWildAnimals" in chaser,
      "-- owner: *\"just npc pawns and wild animals and shit of the gasme\"*, which is a list of "
      "two things; a roster of only people is half an answer")

check("and the humanlike kinds are the ones the inhabitant families already vetted",
      all(name in chaser for name in ('"Pirate"', '"Drifter"', '"Villager"'))
      and "RR_Inhabitant_Psychotic" not in chaser,
      "-- one vetted list of people down here who will hurt you, not two. The names match the "
      "def's own `pawnKindDefNames` without reading the def at runtime")

# **THE LOAD-BEARING CLAIM.** Everything else about the old pursuer followed from the teleport:
# because it never pathfound, it needed its own advance timer, its own loudness rule, its own
# withdrawal counter and its own scripted strike. Nothing may assign a chaser's position.
check("NOTHING TELEPORTS -- no chaser position is ever assigned",
      not re.search(r"pursuer\s*\.\s*Position\s*=", chaser)
      and not re.search(r"pursuer\s*\.\s*Position\s*=", site),
      "-- `pursuer.Position = cell` is what made this not core mechanics: it never walked, never "
      "pathfound and never opened a door, so nothing a player knows about RimWorld applied")

check("AND NOTHING SCRIPTS DAMAGE -- Core's combat does the hurting",
      "TakeDamage(" not in chaser
      and "DamageDefOf" not in chaser,
      "-- the old encounter landed two points of blunt on a named arm, only above 80% health, "
      "then withdrew: the same two points whether the crew fought well or badly")

check("the teleport-era counters are gone, not merely unused",
      "advances" not in site
      and "nextAdvanceTick" not in site
      and "attemptedStrike" not in site
      and "lastObservedCrewRoom" not in site,
      "-- five fields existed only to pace a scripted walk. A real hostile paces itself, and a "
      "dead saved field is a thing somebody later reads as meaningful")

check("THE BESPOKE THING CLASS IS DELETED",
      not os.path.isfile(os.path.join(SRC, "Threats", "Thing_QuietPursuer.cs")),
      "-- `Thing_QuietPursuer : ThingWithComps, IAttackTarget`, whose own comment read *\"No "
      "native pawn AI or unbounded melee attacks\"*")

check("and its ThingDef is out of the package, with the reason left in place",
      "<defName>RR_QuietPursuer</defName>" not in site_objects
      and "RR_QuietPursuer IS RETIRED" in site_objects,
      "-- a def removed with no note is a def somebody re-adds; the owner's direction is in the "
      "file where the def used to be")

check("nothing in the assembly still reaches for the retired def",
      "RR_QuietPursuer" not in chaser
      and "RR_QuietPursuer" not in site
      and "RR_QuietPursuer" not in observations,
      "-- a `GetNamedSilentFail` on a def that no longer exists returns null forever and reports "
      "nothing, which is the quietest possible way for an encounter to stop happening")

# The sighting used to be answered by scanning the map for a def. With a chaser being an ordinary
# hostile, that scan would either find nothing or count every raider on the map as a sighting.
check("A SIGHTING ASKS THE SITE WHICH PAWN THE CHASER IS",
      "site.Chaser" in observations
      and "public Pawn Chaser" in site,
      "-- scanning the map for hostiles would count any raider as an entity observation, which "
      "is a false positive on a contract bonus")

check("THE DRAW IS DERIVED FROM THE BRANCH SEED, NEVER Rand",
      "CampaignSeed.Derive(branchSeed" in chaser
      and not re.search(r"\bRand\s*\.", chaser),
      "-- one opening always meets the same chaser, so a reload cannot reroll what is hunting "
      "you; `Rand` here would make an encounter a save-scum")

check("and the roster is ordered before it is indexed",
      "roster.OrderBy(kind => kind.defName)" in chaser,
      "-- a derived index into an unordered list is only reproducible by luck: def database "
      "order is not a promise, and the same seed would pick different things on different loads")

check("THE DETECTION CAPABILITIES STILL BUY SOMETHING",
      "DetectionRadiusRooms" in chaser
      and '"RR_Cap_Detection"' in chaser
      and '"RR_Cap_EarlyWarning"' in chaser,
      "-- both used to widen the grace before a scripted strike that no longer exists. A "
      "researched capability that silently stops doing anything is worse than one never written")

check("and Detection supersedes EarlyWarning rather than stacking",
      chaser.index('"RR_Cap_Detection"') < chaser.index('"RR_Cap_EarlyWarning"'),
      "-- three rooms, not four. The same relationship the grace calculation it replaces had")

check("REPELLING USES CORE'S OWN FEAR",
      "MentalStateDefOf.PanicFlee" in chaser,
      "-- a hostile that breaks off is a thing RimWorld models. The old one was teleported down "
      "the corridor and its timer reset")

check("and a wild animal chaser is turned manhunter rather than given a faction",
      "MentalStateDefOf.Manhunter" in chaser
      and "Faction hostile = animal ? null : Faction.OfAncientsHostile;" in chaser,
      "-- Core's own way of saying *this one is coming for you*, and it is why a wild animal "
      "chaser needs nothing authored at all")

# **SCOPED TO THE METHOD, AND SHAPE-FREE.** The first draft matched the old code's exact
# three-line layout with a regex, so a plant that reinstated the destroy on a different line
# sailed past it and the suite reported MISSED. Scoped because `StartPursuer` legitimately
# destroys a pawn whose spawn failed -- a file-wide absence claim would be false against
# correct code, which is the other way this claim could have been wrong.
_withdraw = chaser[chaser.index("private void WithdrawPursuer("):]
_withdraw = _withdraw[:_withdraw.index("private Dictionary<int, int> DistancesFrom(")]
check("THE ENCOUNTER ENDING NO LONGER VANISHES THE PAWN",
      "pursuerWithdrawn = true;" in _withdraw
      and "Destroy(" not in _withdraw,
      "-- a dead raider leaves a corpse to strip and a live one may be met again. Vanishing the "
      "thing a crew just fought reads as a bug")

# **A CHASER THAT IS NOT SAVED DISAPPEARS ON RELOAD, SILENTLY.** The encounter flags are
# saved, so losing only the reference leaves the site certain something is hunting the crew
# and unable to say what -- and the readout keeps reporting a room number for a pawn that is
# gone.
check("AND THE CHASER IS SAVED WITH THE SITE",
      'Scribe_References.Look(ref pursuer, "rr_pursuer");' in site,
      "-- the encounter flags persist, so losing only the reference leaves the site certain "
      "something is hunting the crew and unable to say what")

check("the two-rooms-out placement is kept",
      "distances[r.index] == 2" in chaser,
      "-- an encounter that begins on top of you is not an encounter, and this rule was already "
      "right before any of the rest of it was")

check("and an unreachable room still refuses the encounter rather than wasting it",
      "map.reachability.CanReach(possible, p.Position," in chaser
      and "if (distant == null) { return; }" in chaser,
      "-- an unopened room is not a pursuit route; the encounter is retried once exploration "
      "exposes one")

print("")
if failures:
    print("PROOF FAILED: %d claim(s)" % len(failures))
    sys.exit(1)
print("PROOF HELD: what chases a crew is an ordinary pawn, drawn from Core's own kinds and the "
      "biome's animals, hunting with Core's AI")
