# -*- coding: utf-8 -*-
"""Record the two-map answer verbatim, and why the seed-tile route was dropped."""
import io
import os

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
p = os.path.join(REPO, 'docs', 'TODO.md')
s = io.open(p, encoding='utf-8').read()

block = u"""
**Verbatim owner answer (2026-09-29), at the exit-route fork:** *"Two maps at start, coordinate is real (Recommended)"*

- [ ] **"Two maps at start, coordinate is real"** - the solo/group start generates **two** maps. The starting map is an ordinary surface map on the tile the player picked, holding a small concrete shell with one door in it. A **real Backrooms coordinate** is generated alongside, and the starting people and their supplies are put inside it before the player ever sees the surface. The exit is a genuine registered `Emergence` connection from the first tick.
- [ ] **This supersedes the earlier answer** *"Emerges on a fresh tile chosen by the seed"*, and the reason is a hard architectural constraint that was only found by reading `RimroomsPortalNetwork.Register`:
  - `Register` requires **`secondAnchor.Map.Parent as RimroomsDestinationMapParent`** with a matching `CoordinateRecord`. The Backrooms side of any connection must be a real coordinate map.
  - The solo/group start's map **cannot be one**, because `Game.InitNewGame` generates the starting map for a **player `Settlement`** world object and errors without one.
  - So 0.12.0-dev's design - *the starting map IS the coordinate* - is the thing that makes a registered exit impossible. Keeping it would have meant widening the validation that **every existing gate depends on**, which is the riskiest change available.
- [ ] **What this reworks from 0.12.0-dev:** `GenStep_InsideStart` and the `RR_InsideStart` map generator are **retired and archived**; the coordinate is generated by the existing `DestinationService.EnsureSite` through `GenStep_BackroomsDestination`, which is the proven path. `insideStart` stops meaning *"the starting map is a coordinate"* and starts meaning *"the starting people begin in a coordinate alongside the surface map"*.
- [ ] **The cost, stated plainly:** the surface tile is the one the player chose at setup rather than one derived from the seed. The owner took that trade knowingly at the fork.
"""

anchor = u'\n**Verbatim owner direction (2026-09-29), constraining all of the above:**'
assert anchor in s, 'anchor not found'
s = s.replace(anchor, block + anchor, 1)
io.open(p, 'w', encoding='utf-8', newline='').write(s)
print('two-map answer recorded verbatim')
