# -*- coding: utf-8 -*-
"""Rework the solo/group start to two maps with a real coordinate."""
import io
import os
import shutil
import xml.etree.ElementTree as ET

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MOD = os.path.join(REPO, 'Mod', 'Rimrooms - Async Industries', '1.6')


def sub(path, old, new, enc='utf-8-sig'):
    s = io.open(path, encoding=enc).read()
    assert old in s, '%s: anchor missing %r' % (os.path.basename(path), old[:70])
    assert s.count(old) == 1, '%s: anchor not unique' % os.path.basename(path)
    io.open(path, 'w', encoding=enc, newline='').write(s.replace(old, new, 1))


# ------------------------------------------------------------------ archive the retired generator
arc = os.path.join(REPO, 'docs', 'implementation', 'historical-content', '0.12.0-dev')
if not os.path.isdir(arc):
    os.makedirs(arc)
src = os.path.join(REPO, 'src', 'RimroomsAsyncIndustries', 'Scenario', 'GenStep_InsideStart.cs')
body = io.open(src, encoding='utf-8-sig').read()
io.open(os.path.join(arc, 'RETIRED_GENSTEP_INSIDESTART.md'), 'w', encoding='utf-8', newline='').write(
    u"""# GenStep_InsideStart — retired 0.12.2-dev, shipped in 0.12.0-dev

**Archive, not a deletion** (invariant 37).

This generated the solo/group start's map **as** a Backrooms coordinate, using
`GameInitData.mapGeneratorDef`. It worked, it built clean, and the starts proof validated it.

## Why it was retired one checkpoint later

**It could never carry a registered exit**, and the owner's direction requires one at 100%:

> *"the solo/group start in a backroom needs to 100% have a exit to map natural portal on their
> first backrroms level"*

`RimroomsPortalNetwork.Register` requires the Backrooms side of every connection to be a
`RimroomsDestinationMapParent` with a matching `CoordinateRecord`:

```csharp
RimroomsDestinationMapParent site = secondAnchor.Map.Parent as RimroomsDestinationMapParent;
if (coordinate == null || coordinate.site != site || site == null || !site.LayoutReady ||
    site.CoordinateId != coordinateId) { return PortalNetworkResult.UnknownCoordinate; }
```

The **starting** map cannot be one. `Game.InitNewGame` generates it for a player `Settlement`
world object and logs an error without one, so the starting map's parent is always a `Settlement`.

Keeping this design would have meant widening the validation **every existing gate depends on**.
The owner chose the other route at the fork: *"Two maps at start, coordinate is real"*.

## What replaced it

`SoloGroupOpening`, which generates the coordinate through `DestinationService.EnsureSite` — the
same path every gate destination uses — and registers an ordinary `Emergence` connection at the
opening instead of waiting for a survey draw to find one.

## The part of it that survived

`GenStep_BackroomsDestination.BuildShell`, extracted for this class to share, **stays**. It is the
one implementation of the coordinate shell that carries invariant 13, and the destination
generator still calls it.

## The retired source, verbatim

```csharp
""" + body + u"""```
""")
os.remove(src)
print('GenStep_InsideStart archived and removed')

# ------------------------------------------------------------------ remove the retired defs
p = os.path.join(MOD, 'Defs', 'MapGeneratorDefs', 'RR_BackroomsGeneration.xml')
s = io.open(p, encoding='utf-8-sig').read()
i = s.index(u'\n  <!-- The solo/group start\'s map.')
j = s.index(u'</Defs>')
s = s[:i] + u'\n' + s[j:]
io.open(p, 'w', encoding='utf-8-sig', newline='').write(s)
ET.parse(p)
print('RR_InsideStart generator defs removed')

# ------------------------------------------------------------------ the def field
p = os.path.join(REPO, 'src', 'RimroomsAsyncIndustries', 'Scenario', 'RimroomsStartDef.cs')
sub(p, u'''        /// <summary>
        /// This start opens INSIDE a Backrooms coordinate rather than on a surface tile.
        ///
        /// It changes what a layout means. A surface start declares rooms, doors, buildings and
        /// conduits and `GenStep_Headquarters` builds them. An inside start declares none of
        /// those: the map IS the coordinate, generated by `GenStep_InsideStart` from a room
        /// graph, and there is no facility to place because nobody built one.
        /// </summary>
        public bool insideStart;''',
u'''        /// <summary>
        /// The starting people begin **inside a Backrooms coordinate**, alongside the surface map
        /// rather than on it.
        ///
        /// **Reworked in 0.12.2-dev.** It used to mean *the starting map is a coordinate*, which
        /// could never carry a registered exit: `RimroomsPortalNetwork.Register` requires the
        /// Backrooms side of a connection to be a `RimroomsDestinationMapParent`, and the starting
        /// map always belongs to a player `Settlement` because `Game.InitNewGame` demands one.
        ///
        /// Now the surface map is an ordinary map with a small shell and one door on it, a real
        /// coordinate is generated beside it, and <see cref="SoloGroupOpening"/> moves everybody
        /// inside after registering the way out. So an inside start **does** declare a layout —
        /// just a very small one.
        /// </summary>
        public bool insideStart;

        /// <summary>
        /// Which of this start's doors is the way out of the Backrooms.
        ///
        /// Named here rather than guessed. A start that placed two doors and let the opening pick
        /// one would put the exit somewhere different depending on scan order, and the player
        /// would have no way to know which door mattered.
        /// </summary>
        public IntVec3 emergenceDoorCell = IntVec3.Invalid;''')

sub(p, u'''            // An inside start has no facility to declare, and declaring one would be built on
            // top of a coordinate that is already wall to wall.
            if (insideStart && (rooms.Count > 0 || doors.Count > 0 || buildings.Count > 0 || conduits.Count > 0))
            { yield return "An inside start declares no rooms, doors, buildings or conduits; the map is the coordinate."; }
            if (insideStart && (insideStartDepth < 1 || insideStartDepth > 9))
            { yield return "Inside start depth must be between 1 and 9."; }
            if (!insideStart && rooms != null && rooms.Count < 1)
            { yield return "A surface start needs at least one room."; }''',
u'''            if (rooms != null && rooms.Count < 1)
            { yield return "Every start needs at least one room on its surface map."; }
            if (insideStart && (insideStartDepth < 1 || insideStartDepth > 9))
            { yield return "Inside start depth must be between 1 and 9."; }
            // The way out has to be one of this start's own doors. A cell that is not in the
            // doors list has no door generated at it, so the opening would find nothing to mark
            // and the start would have no registered exit at all -- which is the one thing the
            // owner's direction says it must have at 100%.
            if (insideStart && (!emergenceDoorCell.IsValid ||
                doors == null || !doors.Contains(emergenceDoorCell)))
            { yield return "An inside start must name an emergenceDoorCell that is one of its own doors."; }''')
print('RimroomsStartDef reworked')

# ------------------------------------------------------------------ the start def
p = os.path.join(MOD, 'Defs', 'RimroomsStartDefs', 'RR_Starts.xml')
sub(p, u"""    <insideStart>true</insideStart>
    <insideStartDepth>1</insideStartDepth>
    <mapSize>60</mapSize>
    <mapGenerator>RR_InsideStart</mapGenerator>
    <outdoorTerrain>Concrete</outdoorTerrain>
    <floorTerrain>Concrete</floorTerrain>
    <wallStuff>BlocksGranite</wallStuff>
    <!-- The generator decides where anybody can stand, because the rooms are generated. These
         two are required by the shared contract and are never read on an inside start. -->
    <arrivalCell>(30, 0, 30)</arrivalCell>
    <stockCell>(30, 0, 30)</stockCell>
    <rooms />
    <doors />
    <buildings />
    <conduits />""",
u"""    <insideStart>true</insideStart>
    <insideStartDepth>1</insideStartDepth>
    <mapSize>60</mapSize>
    <mapGenerator>RR_Headquarters</mapGenerator>
    <outdoorTerrain>Soil</outdoorTerrain>
    <floorTerrain>Concrete</floorTerrain>
    <wallStuff>BlocksGranite</wallStuff>
    <!-- The surface map holds ONE small concrete shell with ONE door, and nothing else. That
         door is the place the Backrooms comes up, and it is where they will come out. Everything
         a facility needs, they build.

         Reworked in 0.12.2-dev: the starting map used to BE the coordinate, which could never
         carry a registered exit. Now the coordinate is real and generated beside this map, and
         SoloGroupOpening moves everybody into it after registering the way out. -->
    <arrivalCell>(30, 0, 29)</arrivalCell>
    <stockCell>(30, 0, 31)</stockCell>
    <emergenceDoorCell>(30, 0, 27)</emergenceDoorCell>
    <rooms>
      <li><x>27</x><z>27</z><width>7</width><height>7</height><roofed>true</roofed><floor>true</floor></li>
    </rooms>
    <doors>
      <li>(30, 0, 27)</li>
    </doors>
    <buildings />
    <conduits />""")
ET.parse(p)
print('solo/group start def reworked')

# ------------------------------------------------------------------ hook the opening
p = os.path.join(REPO, 'src', 'RimroomsAsyncIndustries', 'Scenario', 'ScenPart_RimroomsStart.cs')
sub(p, u"""            receipt.branchInitialized = true;
            receipt.failure = null;
            SetStartingRelations();""",
u"""            receipt.branchInitialized = true;
            receipt.failure = null;
            // The solo/group opening, after the branch exists and before the welcome letter: it
            // needs a live campaign to mint a coordinate against, and the player should not be
            // told they have arrived until they are actually where they start.
            string openingFailure = SoloGroupOpening.Open(startDef, company, map);
            if (openingFailure != null)
            {
                receipt.failure = openingFailure;
                return CompanyActionResult.Refused(openingFailure);
            }
            SetStartingRelations();""", 'utf-8-sig')
print('opening hooked into PostGameStart')

# ------------------------------------------------------------------ keyed string
p = os.path.join(MOD, 'Languages', 'English', 'Keyed', 'RR_Scenario.xml')
s = io.open(p, encoding='utf-8-sig').read()
assert 'RR_Event_SoloGroupOpening' not in s
key = u'  <RR_Event_SoloGroupOpening>The group started inside, and the way out was already there. Nobody built it and nobody knows who did.</RR_Event_SoloGroupOpening>\n'
i = s.rindex(u'</LanguageData>')
io.open(p, 'w', encoding='utf-8-sig', newline='').write(s[:i] + key + s[i:])
ET.parse(p)
print('keyed string added')
