using System;
using System.Collections.Generic;
using System.Linq;
using RimroomsAsyncIndustries.Company;
using RimroomsAsyncIndustries.Generation;
using RimroomsAsyncIndustries.Portals;
using RimWorld;
using Verse;

namespace RimroomsAsyncIndustries.Scenario
{
    /// <summary>
    /// The solo/group opening: two maps, and the people start on the wrong one.
    ///
    /// **Owner direction, 2026-09-29, verbatim:** *"and remember the solo/group start in a
    /// backroom needs to 100% have a exit to map natural portal on their first backrroms level"*,
    /// and at the fork: ***"Two maps at start, coordinate is real"***.
    ///
    /// ## Why two maps, and not one
    ///
    /// 0.12.0-dev generated the starting map **as** a coordinate. That could never carry a
    /// registered exit, and the reason is a hard constraint in
    /// <see cref="RimroomsPortalNetwork.Register"/>: the Backrooms side of any connection must be
    /// a <see cref="RimroomsDestinationMapParent"/> with a matching <see cref="CoordinateRecord"/>.
    /// The starting map cannot be one, because `Game.InitNewGame` generates it for a player
    /// `Settlement` and errors without one.
    ///
    /// So the surface map is an ordinary map holding a small concrete shell with one door, and
    /// **the coordinate is real** — generated by the same `DestinationService.EnsureSite` path
    /// every gate destination uses. Nothing here is a special case of the portal network; it is
    /// an ordinary `Emergence` connection, registered at startup instead of found by survey.
    ///
    /// ## Why that satisfies "100%"
    ///
    /// `NaturalFrontierService` finds a way out at roughly one door in twelve, and only when a
    /// way home is already marked. **A draw cannot deliver a guarantee.** This registers the
    /// connection directly, once, at the opening, so the exit is not something the player might
    /// find — it is something that is already there.
    ///
    /// ## What it does not decide
    ///
    /// **Whether anybody uses it.** Owner, verbatim: *"this is all open eneded they can play how
    /// they choose"*. The exit exists and is permanently open, which is what a natural gate is
    /// (invariant 12). A group that would rather stay down there, mine the rock and grow food
    /// under thick roof is playing correctly and nothing nudges them.
    /// </summary>
    internal static class SoloGroupOpening
    {
        /// <summary>
        /// Everything the opening needs, in the order it has to happen. Returns a refusal key,
        /// or null on success.
        ///
        /// **Idempotent.** Every step already answers "already done" — the coordinate record,
        /// the site, the emergence mark and the network edge all do — so a retry after a partial
        /// failure finishes the job rather than building a second one.
        /// </summary>
        internal static string Open(RimroomsStartDef start, RimroomsCampaignComponent campaign, Map surface,
            ref string coordinateId)
        {
            // **Any start that names a door gets a natural connection**, not only the
            // inside start. Before 0.12.45-dev this returned here unless `insideStart`, so the
            // Furniture Store -- whose entire premise is a door in the back that should not be
            // there -- began with no Backrooms connection of any kind. Nothing in the
            // headquarters generator creates one, so there was nothing to enter.
            if (start == null || !start.emergenceDoorCell.IsValid) { return null; }
            if (campaign == null || !campaign.CanOperate || surface == null)
            { return "RR_Start_MissingSetup"; }

            // 1. The coordinate. A stable id from the branch, so a reload or a retry resolves to
            //    the same space rather than minting a second one.
            // A retry after a failed attempt reuses the coordinate that attempt created rather
            // than minting a second one.
            CoordinateRecord coordinate = null;
            if (!string.IsNullOrEmpty(coordinateId))
            {
                for (int index = 0; index < campaign.Coordinates.Count; index++)
                {
                    CoordinateRecord known = campaign.Coordinates[index];
                    if (known != null && known.Id == coordinateId) { coordinate = known; break; }
                }
            }
            if (coordinate == null)
            {
                CompanyActionResult created = campaign.CreateDiscoveredCoordinate(
                    "opening", Math.Max(1, start.insideStartDepth), out coordinate);
                if (!created.Success || coordinate == null) { return created.MessageKey ?? "RR_Generation_InvalidRequest"; }
                coordinateId = coordinate.Id;
            }

            // 2. The map for it, through the one path every gate destination already uses.
            Map inside;
            IntVec3 entry;
            CompanyActionResult site = DestinationService.EnsureSite(campaign, coordinate, out inside, out entry);
            if (!site.Success || inside == null || !entry.IsValid) { return site.MessageKey ?? "RR_Generation_OwnerMissing"; }

            // 3. The way out, marked on the surface door the start def named. Marked rather than
            //    assumed: `Mark()` re-checks that the door is on an ordinary branch map with a
            //    standable approach, which is exactly the validation the network will repeat.
            Thing exitDoor = FindExitDoor(start, surface);
            if (exitDoor == null) { return "RR_Emergence_DoorUnavailable"; }
            CompRimroomsEmergence anchor = exitDoor.TryGetComp<CompRimroomsEmergence>();
            if (anchor == null) { return "RR_Emergence_DoorUnavailable"; }
            CompanyActionResult marked = anchor.Mark();
            if (!marked.Success) { return marked.MessageKey ?? "RR_Emergence_DoorUnavailable"; }

            // 4. The connection. The Backrooms end is the coordinate's own threshold anchor, which
            //    is the door the destination generator already placed there.
            Thing threshold = ThresholdOf(inside);
            if (threshold == null) { return "RR_PortalAddress_LocalThresholdUnavailable"; }
            CompanyActionResult registered = PortalAddressService.RegisterEmergenceAddress(
                threshold, PortalAddressService.ApproachCellFor(threshold), anchor);
            if (!registered.Success) { return registered.MessageKey ?? "RR_PortalAddress_InvalidState"; }

            // 5. Put them where they actually start -- **only for a start that begins
            //    inside**. Done last, so a failure above leaves everybody standing safely on
            //    the surface rather than sealed in a coordinate with no registered way out.
            //
            //    A surface start with a natural gate stops here: the connection is registered
            //    and permanently open, and the crew are in their own building looking at a door
            //    that was not there yesterday. Whether they go through is theirs to decide.
            if (start.insideStart)
            {
                // **THEY DO NOT WAKE UP BESIDE THE WAY OUT.** Owner, 2026-10-06: *"the solo start u
                // have to find your way to get out not just have the natural exit gate right next to
                // u in main backroom room at start it needs to be found in the unexplored rooms"*.
                //
                // `entry` is the generator's threshold-room start spot, which is the right answer
                // for an expedition arriving through a machine gate and the wrong one here: the
                // threshold room is where the exit door is. **The party moves; the door does not** --
                // `parent.ReturnAnchor` is every expedition's way home, and relocating it would
                // strand every ordinary crew to fix one opening.
                //
                // Measured in ROOMS over `RoomRecord.Links`, never in cells, because a 300x300
                // coordinate can put a cell far away and still inside the room you woke up in.
                RoomRecord arrivalRoom = SoloGroupArrival.ArrivalRoom(coordinate);
                IntVec3 arrival = SoloGroupArrival.ArrivalCell(inside, arrivalRoom);
                // Falls back to the generator's own cell rather than failing. An opening that is
                // merely too easy is playable; §1.1's solo guarantee is not traded for a nicety.
                MoveOpeningPartyInside(surface, inside, arrival.IsValid ? arrival : entry);
                if (arrival.IsValid)
                {
                    // Distant is not the same as found: the generator unfogs the threshold room, so
                    // without this the exit would sit revealed on the map from the first second.
                    SoloGroupArrival.HideTheWayOut(inside, arrivalRoom,
                        SoloGroupArrival.ThresholdRoom(coordinate));
                }
                campaign.RecordEvent("RR_Event_SoloGroupOpening", coordinate.Id);
            }
            else
            {
                campaign.RecordEvent("RR_Event_NaturalGateOpening", coordinate.Id);
            }
            return null;
        }

        /// <summary>
        /// The door the start def named as the way out.
        ///
        /// Named in the def rather than guessed, because a start that placed two doors and let
        /// this pick one would put the exit somewhere different depending on scan order — and the
        /// player would have no way to know which door was the important one.
        /// </summary>
        private static Thing FindExitDoor(RimroomsStartDef start, Map surface)
        {
            // Offset, because the layout is placed onto whatever map the player chose
            // rather than forcing its own size; see HeadquartersLayout. Reading the authored
            // cell directly would look for a door where no door is.
            IntVec3 cell = start.emergenceDoorCell + HeadquartersLayout.Offset(start, surface.Size);
            if (!cell.IsValid || !cell.InBounds(surface)) { return null; }
            Building edifice = cell.GetEdifice(surface);
            return edifice is Building_Door ? edifice : null;
        }

        /// <summary>The coordinate's own threshold door, placed by the destination generator.</summary>
        private static Thing ThresholdOf(Map inside)
        {
            RimroomsDestinationMapParent parent = inside.Parent as RimroomsDestinationMapParent;
            Thing anchor = parent == null ? null : parent.ReturnAnchor;
            if (anchor != null && anchor.Spawned && !anchor.Destroyed && anchor.Map == inside)
            { return anchor; }
            // A site whose anchor reference is missing is not a reason to pick an arbitrary door:
            // the threshold is where the way home is, and guessing it would put the exit
            // somewhere the generator never intended.
            return null;
        }

        /// <summary>
        /// Moves the starting party and everything they brought from the surface into the
        /// coordinate.
        ///
        /// **Pawns first, then their supplies**, because a supply drop landing on a cell a pawn
        /// is about to occupy is the ordinary way to lose an item. Everything is placed near the
        /// coordinate's entry cell, which the site owner has already validated as standable.
        ///
        /// Only the player's own things move. Nothing on the surface map belongs to anybody else
        /// at this point, but asking is cheaper than assuming, and a mod that added a wandering
        /// animal to a fresh map should not have it teleported into the Backrooms.
        /// </summary>
        private static void MoveOpeningPartyInside(Map surface, Map inside, IntVec3 entry)
        {
            List<Pawn> party = surface.mapPawns.AllPawnsSpawned
                .Where(pawn => pawn != null && pawn.Faction == Faction.OfPlayer)
                .OrderBy(pawn => pawn.thingIDNumber)
                .ToList();
            foreach (Pawn pawn in party)
            {
                if (pawn.Destroyed || !pawn.Spawned) { continue; }
                // A failed or throwing placement puts them back on the surface rather than
                // leaving anybody unspawned. A start that loses a colonist to a placement failure
                // is worse than a start that opens on the surface with the exit already registered.
                Core.HeldCustody.Relocate(pawn, inside, entry, true);
            }

            List<Thing> supplies = surface.listerThings.AllThings
                .Where(thing => thing != null && thing.Spawned && !(thing is Pawn) &&
                    thing.def != null && thing.def.category == ThingCategory.Item)
                .OrderBy(thing => thing.thingIDNumber)
                .ToList();
            foreach (Thing thing in supplies)
            {
                if (thing.Destroyed || !thing.Spawned) { continue; }
                Core.HeldCustody.Relocate(thing, inside, entry, true);
            }
        }
    }
}
