# -*- coding: utf-8 -*-
"""Generate the published wiki's index from the pages themselves.

Why this exists
---------------
**Owner direction, verbatim:** *"and docs and pages when we deploy the wiki and docs on github"*,
*"docs/ root on this repo, github.io for now"*, and the one that decides the shape:
*"the beautiful and masterfully way paossible so the thing needs to NOT pop like a text wall"*.
The queue row adds the rule that matters here: **"Generated, never hand-maintained."**

A hand-written list of pages is a second place the truth lives. Add a page and the list is wrong;
rename one and the list is a broken link. So `docs/_includes/nav.html` is written from whatever is
actually in `docs/wiki/`, and `_layouts/default.html` includes it.

**This is NOT the internal ledger renderer and must never become it.** `tools/make-readable-html.py`
renders `TODO.html` and `NOW.html` into `outputs/readable/` as a reading convenience. The queue row
is explicit that it *"stays an internal reading convenience and is never wired to the published
tree"* -- the work ledger is not public. The two tools share no output directory, and
`check-doc-conformance.py` refuses a published copy of either ledger.

What it writes
--------------
`docs/_includes/nav.html` only. It never touches a page's prose: the title comes from the page's
own first `# ` heading and the one-line summary from its `summary:` front matter, so the page
remains the source of truth and this file remains derived.

Order is declared in SECTIONS rather than alphabetical, because a reader arriving at a wiki wants
*install* before *credits*, and alphabetical would put `backrooms` first and `troubleshooting`
last by accident rather than on purpose. A page not named in SECTIONS still appears, under
"More" -- a new page is never silently dropped from the index.

Usage
-----
    python tools/build-site.py          # write the include
    python tools/build-site.py --check  # fail if it is out of date, for the battery
"""
import io
import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
WIKI = os.path.join(REPO, "docs", "wiki")
INCLUDE = os.path.join(REPO, "docs", "_includes", "nav.html")
NL = chr(10)

# The reading order a newcomer needs, which is not alphabetical. Any page not listed here is
# still published and still indexed, under the last group.
SECTIONS = [
    ("Start", ["index", "install", "first-hour", "scenarios"]),
    ("Playing", ["company", "gates", "backrooms", "interface"]),
    ("Running it", ["mods", "multiplayer", "troubleshooting"]),
    ("About", ["credits", "links"]),
]


def page_title(text, slug):
    """The page's own first heading. Falls back to the slug rather than inventing a title."""
    match = re.search(r"^#\s+(.+?)\s*$", text, re.M)
    return match.group(1).strip() if match else slug.replace("-", " ").capitalize()


def page_summary(text):
    """The `summary:` front matter line, or empty.

    Read from front matter rather than guessed from the first paragraph: a guess would put
    half a sentence in the index the first time somebody opened a page with a note at the top.
    """
    if not text.startswith("---"):
        return ""
    end = text.find(NL + "---", 3)
    if end < 0:
        return ""
    match = re.search(r"^summary:\s*(.+?)\s*$", text[:end], re.M)
    if not match:
        return ""
    return match.group(1).strip().strip('"').strip("'")


def esc(value):
    return (value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            .replace('"', "&quot;"))


def pages():
    found = {}
    for name in sorted(os.listdir(WIKI)):
        if not name.endswith(".md"):
            continue
        slug = name[:-3]
        text = io.open(os.path.join(WIKI, name), encoding="utf-8-sig").read()
        found[slug] = (page_title(text, slug), page_summary(text))
    return found


def render(found):
    lines = []
    lines.append("<!-- GENERATED by tools/build-site.py. Do not edit: edit the pages, then run it.")
    lines.append("     Owner: \"Generated, never hand-maintained.\" `--check` fails the battery")
    lines.append("     when this file and docs/wiki/ disagree. -->")
    placed = set()
    groups = list(SECTIONS)
    extra = [slug for slug in sorted(found) if not any(slug in names for _, names in SECTIONS)]
    if extra:
        groups.append(("More", extra))
    for heading, slugs in groups:
        listed = [slug for slug in slugs if slug in found]
        if not listed:
            continue
        lines.append("")
        lines.append("<h2>%s</h2>" % esc(heading))
        lines.append("<ul>")
        for slug in listed:
            placed.add(slug)
            title, summary = found[slug]
            # `index` is the wiki root, so it is linked as the directory rather than as a file.
            href = "/wiki/" if slug == "index" else "/wiki/%s" % slug
            title_attr = (' title="%s"' % esc(summary)) if summary else ""
            # **Compared against a SLUG, not with `contains`.** `page.url contains '/wiki/'` is
            # true on every page in the wiki, so the index would have been marked as the current
            # page everywhere. The layout derives `pageslug` once from `page.url`; this only has
            # to match it.
            lines.append(
                '  <li><a href="{{ \'%s\' | relative_url }}"%s'
                '{%% if pageslug == \'%s\' %%} aria-current="page"{%% endif %%}>%s</a></li>'
                % (href, title_attr, slug, esc(title)))
        lines.append("</ul>")
    lines.append("")
    return NL.join(lines)


def main():
    if not os.path.isdir(WIKI):
        print("build-site: %s does not exist" % WIKI)
        return 1
    found = pages()
    if not found:
        print("build-site: no pages found in docs/wiki")
        return 1
    rendered = render(found)
    existing = (io.open(INCLUDE, encoding="utf-8").read()
                if os.path.isfile(INCLUDE) else None)

    if "--check" in sys.argv:
        if existing is None:
            print("build-site: docs/_includes/nav.html is missing. Run tools/build-site.py.")
            return 1
        if existing != rendered:
            print("build-site: docs/_includes/nav.html is out of date against docs/wiki/.")
            print("            Run tools/build-site.py and commit the result.")
            return 1
        print("build-site: the generated index matches %d page(s)." % len(found))
        return 0

    directory = os.path.dirname(INCLUDE)
    if not os.path.isdir(directory):
        os.makedirs(directory)
    io.open(INCLUDE, "w", encoding="utf-8", newline=NL).write(rendered)
    missing = [slug for slug in found if slug not in set(
        s for _, names in SECTIONS for s in names)]
    print("build-site: wrote docs/_includes/nav.html for %d page(s)." % len(found))
    if missing:
        print("            indexed under \"More\": %s" % ", ".join(sorted(missing)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
