"""Render the project's key documents as standalone HTML you can just open.

Owner direction, 2026-09-29, verbatim: *"make this html open able ... as if i open this with
edge to read it its all fucked up"* and *"its a massive text wall needs style formating and
beautiful layout"*.

An XSLT stylesheet was tried first and **was the wrong answer**: Chromium blocks XSLT loaded
from a `file://` URL, so Edge showed a blank page instead of raw XML -- worse than the
problem. Standalone HTML with the styling inlined has no such restriction and opens from
anywhere.

Output goes to `outputs/readable/`, beside the mod register, and is regenerated rather than
edited. Nothing here ships in the mod package.

Usage
-----
    python tools/make-readable-html.py
"""

import glob
import io
import os
import re
import sys
import xml.etree.ElementTree as ET

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "outputs", "readable")
ABOUT = os.path.join(REPO, "Mod", "Rimrooms - Async Industries", "About", "About.xml")

STYLE = """
:root { color-scheme: dark; }
* { box-sizing: border-box; }
body {
  margin: 0; padding: 3.5rem 1.5rem;
  background: #14140f; color: #d9d4c4;
  font: 16px/1.7 "Segoe UI", system-ui, -apple-system, sans-serif;
}
main { max-width: 48rem; margin: 0 auto; }
a { color: #c9b96a; }
h1 {
  margin: 0 0 .3rem; font-size: 2.1rem; font-weight: 650;
  color: #e8dfa8; letter-spacing: .01em;
}
.sub { margin: 0 0 2.25rem; color: #8f8a76; }
.meta {
  display: grid; grid-template-columns: max-content 1fr; gap: .45rem 1.5rem;
  margin: 0 0 2.5rem; padding: 1.1rem 1.35rem; border-radius: .6rem;
  background: #1c1c15; border: 1px solid #2e2e22;
}
.meta dt {
  color: #8f8a76; font-size: .78rem; text-transform: uppercase; letter-spacing: .08em;
}
.meta dd { margin: 0; }
.pill {
  display: inline-block; margin: 0 .35rem .35rem 0; padding: .12rem .6rem;
  border-radius: 999px; background: #2a2a1e; border: 1px solid #3a3a2a; font-size: .85rem;
}
h2 {
  margin: 2.5rem 0 .85rem; font-size: .8rem; font-weight: 700;
  text-transform: uppercase; letter-spacing: .15em; color: #c9b96a;
  border-bottom: 1px solid #2e2e22; padding-bottom: .5rem;
}
h3 { margin: 1.8rem 0 .6rem; font-size: 1.05rem; color: #e6e0cd; }
p { margin: 0 0 1.05rem; }
.lede { font-size: 1.1rem; color: #e6e0cd; }
ul { margin: 0 0 1.05rem; padding-left: 1.25rem; }
li { margin: .25rem 0; }
code, pre {
  font-family: "Cascadia Mono", Consolas, monospace; font-size: .9em;
  background: #1c1c15; border: 1px solid #2e2e22; border-radius: .3rem;
}
code { padding: .08rem .35rem; }
pre { padding: .9rem 1.1rem; overflow-x: auto; }
pre code { background: none; border: 0; padding: 0; }
table { border-collapse: collapse; width: 100%; margin: 0 0 1.4rem; font-size: .95rem; }
th, td { text-align: left; padding: .45rem .7rem; border-bottom: 1px solid #2e2e22; }
th { color: #8f8a76; font-size: .78rem; text-transform: uppercase; letter-spacing: .07em; }
.note {
  margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #2e2e22;
  color: #7e7a68; font-size: .85rem;
}
.index li { margin: .5rem 0; }
"""


def esc(text):
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def page(title, body):
    return ("<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">"
            "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
            "<title>%s</title><style>%s</style></head><body><main>%s"
            "<p class=\"note\">Generated by <code>tools/make-readable-html.py</code>. "
            "Regenerate rather than edit; nothing here ships in the mod package.</p>"
            "</main></body></html>\n" % (esc(title), STYLE, body))


def inline(text):
    """The small amount of markdown that actually appears in these documents."""
    text = esc(text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    return text


def render_about():
    root = ET.parse(ABOUT).getroot()

    def value(tag):
        node = root.find(tag)
        return (node.text or "").strip() if node is not None else ""

    versions = "".join('<span class="pill">%s</span>' % esc((li.text or "").strip())
                       for li in root.findall("supportedVersions/li"))
    body = ['<h1>%s</h1>' % esc(value("name")),
            '<p class="sub">by %s</p>' % esc(value("author")),
            '<dl class="meta">',
            '<dt>Version</dt><dd>%s</dd>' % esc(value("modVersion")),
            '<dt>Package</dt><dd><code>%s</code></dd>' % esc(value("packageId")),
            '<dt>Supports</dt><dd>%s</dd>' % versions,
            '</dl>']

    for block in re.split(r"\n\s*\n", value("description")):
        block = " ".join(block.split())
        if not block:
            continue
        if block.startswith("---"):
            body.append("<h2>%s</h2>" % esc(block.strip("- ").strip()))
        elif block.startswith("Development build"):
            body.append('<p class="lede">%s</p>' % esc(block))
        else:
            body.append("<p>%s</p>" % esc(block))
    return page(value("name"), "".join(body))


def render_markdown(path, title):
    lines = io.open(path, encoding="utf-8-sig").read().split("\n")
    body, in_code, in_table = [], False, False

    def close_table():
        if in_table:
            body.append("</table>")

    for line in lines:
        stripped = line.rstrip()
        if stripped.startswith("```"):
            if in_code:
                body.append("</code></pre>")
            else:
                close_table()
                in_table = False
                body.append("<pre><code>")
            in_code = not in_code
            continue
        if in_code:
            body.append(esc(line) + "\n")
            continue

        if stripped.startswith("|") and stripped.endswith("|"):
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            if all(set(c) <= set("-: ") and c for c in cells):
                continue
            if not in_table:
                body.append("<table>")
                in_table = True
                body.append("<tr>%s</tr>" % "".join("<th>%s</th>" % inline(c) for c in cells))
                continue
            body.append("<tr>%s</tr>" % "".join("<td>%s</td>" % inline(c) for c in cells))
            continue
        close_table()
        in_table = False

        if not stripped.strip():
            continue
        heading = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if heading:
            level = min(len(heading.group(1)), 3)
            tag = "h1" if level == 1 else ("h2" if level == 2 else "h3")
            body.append("<%s>%s</%s>" % (tag, inline(heading.group(2)), tag))
            continue
        bullet = re.match(r"^\s*[-*]\s+(.*)$", stripped)
        if bullet:
            if not body or not body[-1].startswith("<ul>"):
                body.append("<ul>")
            body.append("<li>%s</li>" % inline(bullet.group(1)))
            continue
        if body and body[-1].startswith("<li>"):
            body.append("</ul>")
        body.append("<p>%s</p>" % inline(stripped))

    close_table()
    return page(title, "".join(body))


def main():
    if not os.path.isdir(OUT):
        os.makedirs(OUT)

    written = []

    io.open(os.path.join(OUT, "About.html"), "w", encoding="utf-8", newline="").write(render_about())
    written.append(("About.html", "The mod's own description, as a player sees it"))

    docs = [
        ("README.md", "README.html", "Project overview"),
        ("CHANGELOG.md", "CHANGELOG.html", "Every released change"),
        (os.path.join("docs", "NOW.md"), "NOW.html", "What is true right now"),
        (os.path.join("docs", "TODO.md"), "TODO.html", "The working queue"),
        (os.path.join("docs", "ROADMAP.md"), "ROADMAP.html", "Phases and milestones"),
    ]
    for source, target, label in docs:
        full = os.path.join(REPO, source)
        if not os.path.isfile(full):
            continue
        title = os.path.basename(source)
        io.open(os.path.join(OUT, target), "w", encoding="utf-8", newline="").write(
            render_markdown(full, title))
        written.append((target, label))

    index = ['<h1>Rimrooms &mdash; readable</h1>',
             '<p class="sub">Open any of these in a browser.</p>',
             '<ul class="index">']
    for name, label in written:
        index.append('<li><a href="%s">%s</a> &mdash; %s</li>' % (name, name, esc(label)))
    index.append("</ul>")
    io.open(os.path.join(OUT, "index.html"), "w", encoding="utf-8", newline="").write(
        page("Rimrooms - readable", "".join(index)))

    print("written to outputs/readable/")
    for name, _ in [("index.html", "")] + written:
        print("  %s" % name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
